#!/bin/bash

echo "Starting ..."

oc login --insecure-skip-tls-verify -u system:admin
# install istio ##################################################################################################################################################################

oc new-project istio-system
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-egressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-citadel-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-ingressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-cleanup-old-ca-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-post-install-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-sidecar-injector-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-galley-service-account -n istio-system

oc apply -f "releases/istio-$1/install/kubernetes/helm/istio/templates/crds.yaml"
sleep 25
oc apply -f "releases/istio-$1/install/kubernetes/istio-demo.yaml"

oc expose svc istio-ingressgateway
oc expose svc servicegraph
oc expose svc grafana
oc expose svc prometheus
oc expose svc tracing
oc adm policy add-role-to-user admin admin

# install kali ##################################################################################################################################################################

# sleep 120
# # URLS for Jaeger and Grafana
# export JAEGER_URL="http://tracing-istio-system.127.0.0.1.nip.io"
# export GRAFANA_URL="http://grafana-istio-system.127.0.0.1.nip.io"
# # export VERSION_LABEL="v0.9.0"

# curl -L http://git.io/getLatestKiali | bash
